config/routes.rb
Rails.application.routes.draw do |map|

  mount_at = Framey::Engine.config.mount_at

  match mount_at => 'framey/videos#index'
  
  map.resources :videos, :only => [ :index, :show, :new],
                          :controller => "framey/videos",
                          :path_prefix => mount_at,
                          :name_prefix => "framey_"
  post "/framey/callback" => "framey/videos#callback"

end

app/models/framey/video.rb
module Framey
  class Video < ActiveRecord::Base
    set_table_name "framey_videos"    
  end
end

app/controllers/framey/videos_controller.rb
module Framey
  class VideosController < ApplicationController

    unloadable
    
    layout 'framey'  # this allows you to have a gem-wide layout
    
    def new
    
    end
    
    # framey callback
    def callback
      render :text => "" and return unless request.post? && params[:video]

      video = Video.create!({
        :name => params[:video][:name],
        :filesize => params[:video][:filesize],
        :duration => params[:video][:duration],
        :state => params[:video][:state],
        :views => params[:video][:views],
        :flv_url => params[:video][:flv_url],
        :mp4_url => params[:video][:mp4_url],
        :small_thumbnail_url => params[:video][:small_thumbnail_url],
        :medium_thumbnail_url => params[:video][:medium_thumbnail_url],          
        :large_thumbnail_url => params[:video][:large_thumbnail_url]
      })

      render :text => "" and return
    end
    
    def index
      @videos = Framey::Video.paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
      
    end
    
    def show
      @video = Framey::Video.find_by_name(params[:id])
    end
    
  end
end

app/helpers/application_helper.rb
## Look in lib/application_helper.rb
## I can't figure out how to get it included unless I put it that directory

app/helpers/framey/videos_helper.rb
module Framey
  module VideosHelper
  end
end

app/views/framey/videos/index.html.erb
<h1> Previously recorded videos </h1>

<% if !@videos.empty? %>
	<% @videos.each do |video|%>
	
		<div class="framey_video_profile">
			<span class="framey_video_thumbnail">
			<a href="<%= framey_video_path(video.name)%>">	
			<%= image_tag video.medium_thumbnail_url%>
			</a>
			</span>
			<span class="framey_video_info">
				<div class="framey_video_name">
					Name: <a href="<%= framey_video_path(video.name)%>"><%= video.name %></a>
				</div>
				<div class="framey_video_duration">
					Length: <%= video.duration %> seconds
				</div>
				<div class="framey_video_filesize">
					Filesize: <%= video.filesize / 1024 %> KB
				</div>
				<div class="framey_video_date">
					Created at: <%= video.created_at %>
				</div>								
			</span>
		</div>
		<hr/>


	<%end%>
<% else %>
	<h3>No videos were recorded, yet </h3>
<% end %>
<%= will_paginate @videos %>

app/views/framey/videos/new.html.erb
<h1>Record a video</h1>
<div id="framey_recoder">
	<%= render_recorder({:max_time => 60}) %>
</div>

app/views/framey/videos/show.html.erb
<h1>Play Video</h1>
<div id="framey_player_container">
	

<%= render_player({
     :video_url => @video.flv_url,          
     :thumbnail_url => @video.medium_thumbnail_url,
     :progress_bar_color => "0x123456",
     :volume_bar_color => "0x123456"
   }) %>
	
	
	<div class="framey_video_profile">
		<span class="framey_video_info">
			<div class="framey_video_name">
				Name: <%= @video.name %>
			</div>
			<div class="framey_video_duration">
				Length: <%= @video.duration %> seconds
			</div>
			<div class="framey_video_filesize">
				Filesize: <%= @video.filesize / 1024 %> KB
			</div>
			<div class="framey_video_date">
				Created at: <%= @video.created_at %>
			</div>								
		</span>
	</div>
</div>

app/views/layouts/framey.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Framey</title>
<%= stylesheet_link_tag("framey") %>
<%= javascript_include_tag "swfobject" %>
</head>
<body>
	<div id="framey_bg">
		<div id="framey_content_container">
			<%= yield %>		
		
			<div id="framey_footer">
				<%= link_to "record new", new_framey_video_path %> | <%= link_to "view videos", framey_videos_path %>
			</div>
		
		</div>
	</div>
</body>

</html>